language: node_js
after_success:
- find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://old.emajjin.org/new/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;